[package]
name = "dipboy"
version = "0.1.0"
authors = ["Siobhán Sterrett <siobhan.sterrett@braze.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = { version = "1.5", features = ["serde"] }
